workflows:
  cabai-ai-v3:
    name: Cabai AI Farm V3

    environment:
      flutter: stable

    scripts:
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
