name: cabai_ai_farm_v3
description: Cabai Agritech AI System V3
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.11.0
  firebase_database: ^12.4.4
  flutter_local_notifications: ^22.0.1
  fl_chart: ^1.2.0
  http: ^1.2.0
  intl: ^0.20.2

flutter:
  uses-material-design: true
