name: cabai_ai_farm_v3
description: Cabai Agritech AI System V3
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.3.0
  firebase_database: ^11.0.0
  flutter_local_notifications: ^17.0.0
  fl_chart: ^0.68.0
  http: ^1.2.0
  intl: ^0.19.0

flutter:
  uses-material-design: true
